language: go

go:
- 1.12.x

env:
- POSTGRESQL_IMAGE=postgres:9.1
- POSTGRESQL_IMAGE=postgres:9.2
- POSTGRESQL_IMAGE=postgres:9.3
- POSTGRESQL_IMAGE=postgres:9.4
- POSTGRESQL_IMAGE=postgres:9.5
- POSTGRESQL_IMAGE=postgres:9.6
- POSTGRESQL_IMAGE=postgres:10
- POSTGRESQL_IMAGE=postgres:11

services:
- docker

go_import_path: github.com/percona/postgres_exporter

before_script:
- sudo service postgresql stop
- docker --version
- docker-compose --version
- docker-compose up -d

script:
- make
- make test

notifications:
  email: false
